# Lectures and Presentations

Several recorded lectures and talks from recent events.

## Wetlandscapes: Land-use legacies and water quality futures

An invited seminar jointly presented by Dr Kimberly Van Meter and I at the Water, Wetlands, and Watersheds Seminar Series hosted by the Howard T. Odum Center for Wetlands at the University of Florida (Jan 13, 2021)


::: {align="center"}
<iframe width="560" height="315" src="https://www.youtube.com/embed/2sgdS-4XmTw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
:::


## Biogeochemical hotspots: The role of small wetlands in landscape nutrient processing

An invited lecture for a senior undergraduate course (aquatic ecology) on the role of small wetlands in removing nitrogen and phosphorus in the landscape (Spring 2020)


::: {align="center"}
<iframe width="560" height="315" src="https://www.youtube.com/embed/-vixeVeaFBQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
:::


## Understanding head potentials in aquifer/aquitard systems

A presentation for an environmental fluid mechanics course on differentiating piezometric and potentiometric head in groundwater systems (Dec 2012)



::: {align="center"}
<iframe width="560" height="315" src="https://www.youtube.com/embed/z8Z2EdZgnlQ" frameborder="0" allowfullscreen>

</iframe>
:::


